spring.application.name=mkpay

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mkpay_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.db.enabled=true

resilience4j.ratelimiter.instances.paymentApi.limitForPeriod=10
resilience4j.ratelimiter.instances.paymentApi.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.paymentApi.timeoutDuration=0ms

mkpay.api.key=${MKPAY_API_KEY:mkpay-test-api-key-2026}