create table banks
(
    id                 bigint generated by default as identity
        primary key,
    active             boolean      not null,
    code               varchar(10)  not null
        constraint ukhim9ibq87o3130hicv5qo2nig
            unique,
    name               varchar(255) not null,
    settlement_account varchar(255) not null
);


create table bank_accounts
(
    id             bigint generated by default as identity
        primary key,
    account_number varchar(255)   not null
        constraint ukr9gi1et82prjsig51uqxj2qm6
            unique,
    balance        numeric(15, 2) not null,
    owner_name     varchar(255)   not null,
    version        bigint         not null,
    bank_id        bigint         not null
        constraint fk8ngd2pjw12xdt5wasywldwjy3
            references banks
);



create table payments
(
    id              uuid           not null
        primary key,
    amount          numeric(15, 2) not null,
    created_at      timestamp(6)   not null,
    currency        varchar(3)     not null,
    failure_reason  varchar(255),
    recipient_phone varchar(255)   not null,
    sender_phone    varchar(255)   not null,
    state           varchar(255)   not null
        constraint payments_state_check
            check ((state)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'DEBIT_INITIATED'::character varying, 'DEBIT_SUCCESS'::character varying, 'CREDIT_INITIATED'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])),
    updated_at      timestamp(6)   not null,
    idempotency_key varchar(255)
        unique
);


create table phone_aliases
(
    id              bigint generated by default as identity
        primary key,
    phone_number    varchar(15) not null
        constraint ukhkx8bx9vc7op1ohdh7h12bckl
            unique,
    bank_account_id bigint      not null
        constraint fkqtijq2ilk3p1dnucq054ky8p4
            references bank_accounts
);



create table payment_audit_events
(
    id         uuid         not null
        primary key,
    details    varchar(255),
    payment_id uuid         not null constraint fk_payment_audit_events_payment
        references payments(id),
    state      varchar(255) not null
        constraint payment_audit_events_state_check
            check ((state)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'DEBIT_INITIATED'::character varying, 'DEBIT_SUCCESS'::character varying, 'CREDIT_INITIATED'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])),
    timestamp  timestamp(6) not null
);